todos/todoapp/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path("", TodoListList.as_view(), name="viewlists"),
    path("createlist", TodoListCreate.as_view(), name="createlist"),
    path("updatelist/<pk>", TodoListUpdate.as_view(), name="updatelist"),
    path("deletelist/<pk>", TodoListDelete.as_view(), name="deletelist")
]

todos/todos/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("todoapp.urls"))
]

todos/todoapp/models.py
from django.db import models

# Create your models here.
class TodoList(models.Model):
  title = models.CharField(max_length=20)

  def get_absolute_url(self):
    return "/"

  def str(self):
    return self.title

class TodoItem(models.Model):
  text = models.CharField(max_length=30)
  checked = models.BooleanField(default=False)
  todo_list = models.ForeignKey(TodoList, on_delete=models.CASCADE)

  def str(self):
    return self.text

todos/todoapp/forms.py
from django import forms
from .models import *

class TodoListForm(forms.ModelForm):
  def __init__(self, *args, **kwargs):
    super(TodoListForm, self).__init__(*args, **kwargs)
    for visible in self.visible_fields():
      visible.field.widget.attrs['class'] = 'form-field'

  class Meta:
    model = TodoList
    fields = ("title",)

todos/todoapp/views.py
from django.views.generic import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import *
from .forms import *

# Create your views here.
class TodoListList(ListView):
  model = TodoList
  template_name = "todoapp/index.html"

class TodoListCreate(CreateView):
  model = TodoList
  form_class = TodoListForm
  template_name = "todoapp/todo-list-create.html"

class TodoListUpdate(UpdateView):
  model = TodoList
  form_class = TodoListForm
  template_name = "todoapp/todo-list-update.html"

class TodoListDelete(DeleteView):
  model = TodoList
  template_name = "todoapp/todo-list-delete.html"
  success_url = "/"

todos/todoapp/templates/todoapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  {% block head %}
  {% endblock %}
</head>
<body>
  <div class="content-wrapper">
    {% block content %}
    {% endblock %}
  </div>
</body>
</html>

todos/todoapp/templates/todoapp/index.html
{% extends "todoapp/base.html" %}

{% load static %}

{% block head %}
<title>Lists</title>
<script src="https://kit.fontawesome.com/38fe2e90c2.js" crossorigin="anonymous"></script>
<link rel="stylesheet" href="{% static 'todoapp/style.css' %}">
{% endblock %}

{% block content %}
<h1 class="title">Lists</h1>
<table class="table">
  {% for todo_list in todolist_list %}
  <tr>
    <td class="text-field">{{ todo_list.title }}</td>
    <td class="button-field">
      <a class="table-button delete-button" href="{% url 'deletelist' todo_list.id %}">
        <i class="fa-solid fa-trash-can"></i>
      </a>
      <a class="table-button update-button" href="{% url 'updatelist' todo_list.id %}">
        <i class="fa-solid fa-pencil"></i>
      </a>
    </td>
  </tr>
  {% endfor %}
  <tfoot>
    <a class="create-button" href="{% url 'createlist' %}">+ Create list</a>
  </tfoot>
</table>
{% endblock %}

todos/todoapp/templates/todoapp/todo-list-create.html
{% extends "todoapp/base.html" %}

{% load static %}

{% block head %}
<title>Create list</title>
<link rel="stylesheet" href="{% static 'todoapp/style.css' %}">
{% endblock %}

{% block content %}
<h1 class="title">Create list</h1>
<form action="" method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Create">
</form>
{% endblock %}

todos/todoapp/templates/todoapp/todo-list-delete.html
{% extends "todoapp/base.html" %}

{% load static %}

{% block head %}
<title>Create list</title>
<link rel="stylesheet" href="{% static 'todoapp/style.css' %}">
{% endblock %}

{% block content %}
<h1 class="title">Delete list: {{ todolist.title }}</h1>
<p>
  Are you sure you want to delete {{ todolist.title }}?
  All todos inside this list will be lost!
</p>
<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Delete">
</form>
{% endblock %}

todos/todoapp/templates/todoapp/todo-list-update.html
{% extends "todoapp/base.html" %}

{% load static %}

{% block head %}
<title>Update list</title>
<link rel="stylesheet" href="{% static 'todoapp/style.css' %}">
{% endblock %}

{% block content %}
<h1 class="title">Update list</h1>
<form action="" method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Save">
</form>
{% endblock %}